apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: nginx-oinam-1
      image: nginx
      ports:
        - containerPort: 8080
	  - name: nginx-watcher
	    image: afakharany/watcher
      ports:
        - containerPort: 8081
