apiVersion: v1
kind: Pod
metadata: 
  name: pod3
  labels:
    app: helloworld   
spec: 
  containers: 
    - name: python-demo 
      image: oinamibomcha/my-python-repo     
      ports:
      - name: python-port
        containerPort: 8080
